[versions]
kotlin = "2.2.21"
kotest = "5.9.1"
reactor = "3.6.11"

[libraries]
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
reactor-core = { group = "io.projectreactor", name = "reactor-core", version.ref = "reactor" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
